/*
 * generated by Xtext 2.25.0
 */
package pazmysaz.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPykeScopeProvider extends DelegatingScopeProvider {
}
