/**
 * generated by Xtext 2.25.0
 */
package pazmysaz.pyke;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see pazmysaz.pyke.PykePackage
 * @generated
 */
public interface PykeFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PykeFactory eINSTANCE = pazmysaz.pyke.impl.PykeFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Dashboard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dashboard</em>'.
   * @generated
   */
  Dashboard createDashboard();

  /**
   * Returns a new object of class '<em>Trend Summary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trend Summary</em>'.
   * @generated
   */
  TrendSummary createTrendSummary();

  /**
   * Returns a new object of class '<em>Distribution Summary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Distribution Summary</em>'.
   * @generated
   */
  DistributionSummary createDistributionSummary();

  /**
   * Returns a new object of class '<em>Label Summary</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label Summary</em>'.
   * @generated
   */
  LabelSummary createLabelSummary();

  /**
   * Returns a new object of class '<em>Identity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Identity</em>'.
   * @generated
   */
  Identity createIdentity();

  /**
   * Returns a new object of class '<em>Report</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Report</em>'.
   * @generated
   */
  Report createReport();

  /**
   * Returns a new object of class '<em>Section</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Section</em>'.
   * @generated
   */
  Section createSection();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PykePackage getPykePackage();

} //PykeFactory
