/**
 * generated by Xtext 2.25.0
 */
package pazmysaz.pyke;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see pazmysaz.pyke.PykeFactory
 * @model kind="package"
 * @generated
 */
public interface PykePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pyke";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Pyke.pazmysaz";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pyke";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PykePackage eINSTANCE = pazmysaz.pyke.impl.PykePackageImpl.init();

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.DashboardImpl <em>Dashboard</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.DashboardImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getDashboard()
   * @generated
   */
  int DASHBOARD = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Identity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__IDENTITY = 1;

  /**
   * The feature id for the '<em><b>Label Summary</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__LABEL_SUMMARY = 2;

  /**
   * The feature id for the '<em><b>Distribution Summary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__DISTRIBUTION_SUMMARY = 3;

  /**
   * The feature id for the '<em><b>Trend Summary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__TREND_SUMMARY = 4;

  /**
   * The feature id for the '<em><b>Report</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD__REPORT = 5;

  /**
   * The number of structural features of the '<em>Dashboard</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DASHBOARD_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.TrendSummaryImpl <em>Trend Summary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.TrendSummaryImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getTrendSummary()
   * @generated
   */
  int TREND_SUMMARY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY__NAME = 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY__LHS = 1;

  /**
   * The feature id for the '<em><b>Mhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY__MHS = 2;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY__RHS = 3;

  /**
   * The feature id for the '<em><b>Edge</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY__EDGE = 4;

  /**
   * The number of structural features of the '<em>Trend Summary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREND_SUMMARY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.DistributionSummaryImpl <em>Distribution Summary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.DistributionSummaryImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getDistributionSummary()
   * @generated
   */
  int DISTRIBUTION_SUMMARY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY__NAME = 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY__LHS = 1;

  /**
   * The feature id for the '<em><b>Mhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY__MHS = 2;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY__RHS = 3;

  /**
   * The feature id for the '<em><b>Edge</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY__EDGE = 4;

  /**
   * The number of structural features of the '<em>Distribution Summary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTRIBUTION_SUMMARY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.LabelSummaryImpl <em>Label Summary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.LabelSummaryImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getLabelSummary()
   * @generated
   */
  int LABEL_SUMMARY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY__NAME = 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY__LHS = 1;

  /**
   * The feature id for the '<em><b>Mhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY__MHS = 2;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY__RHS = 3;

  /**
   * The feature id for the '<em><b>Edge</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY__EDGE = 4;

  /**
   * The number of structural features of the '<em>Label Summary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SUMMARY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.IdentityImpl <em>Identity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.IdentityImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getIdentity()
   * @generated
   */
  int IDENTITY = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Lhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__LHS = 1;

  /**
   * The feature id for the '<em><b>Mhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__MHS = 2;

  /**
   * The feature id for the '<em><b>Rhs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__RHS = 3;

  /**
   * The feature id for the '<em><b>Edge</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY__EDGE = 4;

  /**
   * The number of structural features of the '<em>Identity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTITY_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.ReportImpl <em>Report</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.ReportImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getReport()
   * @generated
   */
  int REPORT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPORT__NAME = 0;

  /**
   * The feature id for the '<em><b>Section</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPORT__SECTION = 1;

  /**
   * The number of structural features of the '<em>Report</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPORT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.impl.SectionImpl <em>Section</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.impl.SectionImpl
   * @see pazmysaz.pyke.impl.PykePackageImpl#getSection()
   * @generated
   */
  int SECTION = 6;

  /**
   * The feature id for the '<em><b>Presentation Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__PRESENTATION_TYPE = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION__VALUE = 2;

  /**
   * The number of structural features of the '<em>Section</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link pazmysaz.pyke.Widget <em>Widget</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see pazmysaz.pyke.Widget
   * @see pazmysaz.pyke.impl.PykePackageImpl#getWidget()
   * @generated
   */
  int WIDGET = 7;


  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.Dashboard <em>Dashboard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dashboard</em>'.
   * @see pazmysaz.pyke.Dashboard
   * @generated
   */
  EClass getDashboard();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Dashboard#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.Dashboard#getName()
   * @see #getDashboard()
   * @generated
   */
  EAttribute getDashboard_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Dashboard#getIdentity <em>Identity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Identity</em>'.
   * @see pazmysaz.pyke.Dashboard#getIdentity()
   * @see #getDashboard()
   * @generated
   */
  EReference getDashboard_Identity();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Dashboard#getLabelSummary <em>Label Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Label Summary</em>'.
   * @see pazmysaz.pyke.Dashboard#getLabelSummary()
   * @see #getDashboard()
   * @generated
   */
  EReference getDashboard_LabelSummary();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Dashboard#isDistributionSummary <em>Distribution Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distribution Summary</em>'.
   * @see pazmysaz.pyke.Dashboard#isDistributionSummary()
   * @see #getDashboard()
   * @generated
   */
  EAttribute getDashboard_DistributionSummary();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Dashboard#isTrendSummary <em>Trend Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trend Summary</em>'.
   * @see pazmysaz.pyke.Dashboard#isTrendSummary()
   * @see #getDashboard()
   * @generated
   */
  EAttribute getDashboard_TrendSummary();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Dashboard#getReport <em>Report</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Report</em>'.
   * @see pazmysaz.pyke.Dashboard#getReport()
   * @see #getDashboard()
   * @generated
   */
  EReference getDashboard_Report();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.TrendSummary <em>Trend Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trend Summary</em>'.
   * @see pazmysaz.pyke.TrendSummary
   * @generated
   */
  EClass getTrendSummary();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.TrendSummary#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.TrendSummary#getName()
   * @see #getTrendSummary()
   * @generated
   */
  EAttribute getTrendSummary_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.TrendSummary#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see pazmysaz.pyke.TrendSummary#getLhs()
   * @see #getTrendSummary()
   * @generated
   */
  EReference getTrendSummary_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.TrendSummary#getMhs <em>Mhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mhs</em>'.
   * @see pazmysaz.pyke.TrendSummary#getMhs()
   * @see #getTrendSummary()
   * @generated
   */
  EReference getTrendSummary_Mhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.TrendSummary#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see pazmysaz.pyke.TrendSummary#getRhs()
   * @see #getTrendSummary()
   * @generated
   */
  EReference getTrendSummary_Rhs();

  /**
   * Returns the meta object for the containment reference list '{@link pazmysaz.pyke.TrendSummary#getEdge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edge</em>'.
   * @see pazmysaz.pyke.TrendSummary#getEdge()
   * @see #getTrendSummary()
   * @generated
   */
  EReference getTrendSummary_Edge();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.DistributionSummary <em>Distribution Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distribution Summary</em>'.
   * @see pazmysaz.pyke.DistributionSummary
   * @generated
   */
  EClass getDistributionSummary();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.DistributionSummary#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.DistributionSummary#getName()
   * @see #getDistributionSummary()
   * @generated
   */
  EAttribute getDistributionSummary_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.DistributionSummary#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see pazmysaz.pyke.DistributionSummary#getLhs()
   * @see #getDistributionSummary()
   * @generated
   */
  EReference getDistributionSummary_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.DistributionSummary#getMhs <em>Mhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mhs</em>'.
   * @see pazmysaz.pyke.DistributionSummary#getMhs()
   * @see #getDistributionSummary()
   * @generated
   */
  EReference getDistributionSummary_Mhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.DistributionSummary#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see pazmysaz.pyke.DistributionSummary#getRhs()
   * @see #getDistributionSummary()
   * @generated
   */
  EReference getDistributionSummary_Rhs();

  /**
   * Returns the meta object for the containment reference list '{@link pazmysaz.pyke.DistributionSummary#getEdge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edge</em>'.
   * @see pazmysaz.pyke.DistributionSummary#getEdge()
   * @see #getDistributionSummary()
   * @generated
   */
  EReference getDistributionSummary_Edge();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.LabelSummary <em>Label Summary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label Summary</em>'.
   * @see pazmysaz.pyke.LabelSummary
   * @generated
   */
  EClass getLabelSummary();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.LabelSummary#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.LabelSummary#getName()
   * @see #getLabelSummary()
   * @generated
   */
  EAttribute getLabelSummary_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.LabelSummary#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see pazmysaz.pyke.LabelSummary#getLhs()
   * @see #getLabelSummary()
   * @generated
   */
  EReference getLabelSummary_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.LabelSummary#getMhs <em>Mhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mhs</em>'.
   * @see pazmysaz.pyke.LabelSummary#getMhs()
   * @see #getLabelSummary()
   * @generated
   */
  EReference getLabelSummary_Mhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.LabelSummary#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see pazmysaz.pyke.LabelSummary#getRhs()
   * @see #getLabelSummary()
   * @generated
   */
  EReference getLabelSummary_Rhs();

  /**
   * Returns the meta object for the containment reference list '{@link pazmysaz.pyke.LabelSummary#getEdge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edge</em>'.
   * @see pazmysaz.pyke.LabelSummary#getEdge()
   * @see #getLabelSummary()
   * @generated
   */
  EReference getLabelSummary_Edge();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.Identity <em>Identity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identity</em>'.
   * @see pazmysaz.pyke.Identity
   * @generated
   */
  EClass getIdentity();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Identity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.Identity#getName()
   * @see #getIdentity()
   * @generated
   */
  EAttribute getIdentity_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Identity#getLhs <em>Lhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lhs</em>'.
   * @see pazmysaz.pyke.Identity#getLhs()
   * @see #getIdentity()
   * @generated
   */
  EReference getIdentity_Lhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Identity#getMhs <em>Mhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mhs</em>'.
   * @see pazmysaz.pyke.Identity#getMhs()
   * @see #getIdentity()
   * @generated
   */
  EReference getIdentity_Mhs();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Identity#getRhs <em>Rhs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rhs</em>'.
   * @see pazmysaz.pyke.Identity#getRhs()
   * @see #getIdentity()
   * @generated
   */
  EReference getIdentity_Rhs();

  /**
   * Returns the meta object for the containment reference list '{@link pazmysaz.pyke.Identity#getEdge <em>Edge</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Edge</em>'.
   * @see pazmysaz.pyke.Identity#getEdge()
   * @see #getIdentity()
   * @generated
   */
  EReference getIdentity_Edge();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.Report <em>Report</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Report</em>'.
   * @see pazmysaz.pyke.Report
   * @generated
   */
  EClass getReport();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Report#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see pazmysaz.pyke.Report#getName()
   * @see #getReport()
   * @generated
   */
  EAttribute getReport_Name();

  /**
   * Returns the meta object for the containment reference '{@link pazmysaz.pyke.Report#getSection <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Section</em>'.
   * @see pazmysaz.pyke.Report#getSection()
   * @see #getReport()
   * @generated
   */
  EReference getReport_Section();

  /**
   * Returns the meta object for class '{@link pazmysaz.pyke.Section <em>Section</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Section</em>'.
   * @see pazmysaz.pyke.Section
   * @generated
   */
  EClass getSection();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Section#getPresentationType <em>Presentation Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Presentation Type</em>'.
   * @see pazmysaz.pyke.Section#getPresentationType()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_PresentationType();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Section#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see pazmysaz.pyke.Section#getSource()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Source();

  /**
   * Returns the meta object for the attribute '{@link pazmysaz.pyke.Section#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see pazmysaz.pyke.Section#getValue()
   * @see #getSection()
   * @generated
   */
  EAttribute getSection_Value();

  /**
   * Returns the meta object for enum '{@link pazmysaz.pyke.Widget <em>Widget</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Widget</em>'.
   * @see pazmysaz.pyke.Widget
   * @generated
   */
  EEnum getWidget();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PykeFactory getPykeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.DashboardImpl <em>Dashboard</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.DashboardImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getDashboard()
     * @generated
     */
    EClass DASHBOARD = eINSTANCE.getDashboard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DASHBOARD__NAME = eINSTANCE.getDashboard_Name();

    /**
     * The meta object literal for the '<em><b>Identity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DASHBOARD__IDENTITY = eINSTANCE.getDashboard_Identity();

    /**
     * The meta object literal for the '<em><b>Label Summary</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DASHBOARD__LABEL_SUMMARY = eINSTANCE.getDashboard_LabelSummary();

    /**
     * The meta object literal for the '<em><b>Distribution Summary</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DASHBOARD__DISTRIBUTION_SUMMARY = eINSTANCE.getDashboard_DistributionSummary();

    /**
     * The meta object literal for the '<em><b>Trend Summary</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DASHBOARD__TREND_SUMMARY = eINSTANCE.getDashboard_TrendSummary();

    /**
     * The meta object literal for the '<em><b>Report</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DASHBOARD__REPORT = eINSTANCE.getDashboard_Report();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.TrendSummaryImpl <em>Trend Summary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.TrendSummaryImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getTrendSummary()
     * @generated
     */
    EClass TREND_SUMMARY = eINSTANCE.getTrendSummary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREND_SUMMARY__NAME = eINSTANCE.getTrendSummary_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREND_SUMMARY__LHS = eINSTANCE.getTrendSummary_Lhs();

    /**
     * The meta object literal for the '<em><b>Mhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREND_SUMMARY__MHS = eINSTANCE.getTrendSummary_Mhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREND_SUMMARY__RHS = eINSTANCE.getTrendSummary_Rhs();

    /**
     * The meta object literal for the '<em><b>Edge</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TREND_SUMMARY__EDGE = eINSTANCE.getTrendSummary_Edge();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.DistributionSummaryImpl <em>Distribution Summary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.DistributionSummaryImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getDistributionSummary()
     * @generated
     */
    EClass DISTRIBUTION_SUMMARY = eINSTANCE.getDistributionSummary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTRIBUTION_SUMMARY__NAME = eINSTANCE.getDistributionSummary_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION_SUMMARY__LHS = eINSTANCE.getDistributionSummary_Lhs();

    /**
     * The meta object literal for the '<em><b>Mhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION_SUMMARY__MHS = eINSTANCE.getDistributionSummary_Mhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION_SUMMARY__RHS = eINSTANCE.getDistributionSummary_Rhs();

    /**
     * The meta object literal for the '<em><b>Edge</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DISTRIBUTION_SUMMARY__EDGE = eINSTANCE.getDistributionSummary_Edge();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.LabelSummaryImpl <em>Label Summary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.LabelSummaryImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getLabelSummary()
     * @generated
     */
    EClass LABEL_SUMMARY = eINSTANCE.getLabelSummary();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL_SUMMARY__NAME = eINSTANCE.getLabelSummary_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_SUMMARY__LHS = eINSTANCE.getLabelSummary_Lhs();

    /**
     * The meta object literal for the '<em><b>Mhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_SUMMARY__MHS = eINSTANCE.getLabelSummary_Mhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_SUMMARY__RHS = eINSTANCE.getLabelSummary_Rhs();

    /**
     * The meta object literal for the '<em><b>Edge</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_SUMMARY__EDGE = eINSTANCE.getLabelSummary_Edge();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.IdentityImpl <em>Identity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.IdentityImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getIdentity()
     * @generated
     */
    EClass IDENTITY = eINSTANCE.getIdentity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IDENTITY__NAME = eINSTANCE.getIdentity_Name();

    /**
     * The meta object literal for the '<em><b>Lhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTITY__LHS = eINSTANCE.getIdentity_Lhs();

    /**
     * The meta object literal for the '<em><b>Mhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTITY__MHS = eINSTANCE.getIdentity_Mhs();

    /**
     * The meta object literal for the '<em><b>Rhs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTITY__RHS = eINSTANCE.getIdentity_Rhs();

    /**
     * The meta object literal for the '<em><b>Edge</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTITY__EDGE = eINSTANCE.getIdentity_Edge();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.ReportImpl <em>Report</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.ReportImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getReport()
     * @generated
     */
    EClass REPORT = eINSTANCE.getReport();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPORT__NAME = eINSTANCE.getReport_Name();

    /**
     * The meta object literal for the '<em><b>Section</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPORT__SECTION = eINSTANCE.getReport_Section();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.impl.SectionImpl <em>Section</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.impl.SectionImpl
     * @see pazmysaz.pyke.impl.PykePackageImpl#getSection()
     * @generated
     */
    EClass SECTION = eINSTANCE.getSection();

    /**
     * The meta object literal for the '<em><b>Presentation Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__PRESENTATION_TYPE = eINSTANCE.getSection_PresentationType();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__SOURCE = eINSTANCE.getSection_Source();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SECTION__VALUE = eINSTANCE.getSection_Value();

    /**
     * The meta object literal for the '{@link pazmysaz.pyke.Widget <em>Widget</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see pazmysaz.pyke.Widget
     * @see pazmysaz.pyke.impl.PykePackageImpl#getWidget()
     * @generated
     */
    EEnum WIDGET = eINSTANCE.getWidget();

  }

} //PykePackage
