/**
 * generated by Xtext 2.25.0
 */
package pazmysaz.pyke;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link pazmysaz.pyke.Section#getPresentationType <em>Presentation Type</em>}</li>
 *   <li>{@link pazmysaz.pyke.Section#getSource <em>Source</em>}</li>
 *   <li>{@link pazmysaz.pyke.Section#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see pazmysaz.pyke.PykePackage#getSection()
 * @model
 * @generated
 */
public interface Section extends EObject
{
  /**
   * Returns the value of the '<em><b>Presentation Type</b></em>' attribute.
   * The literals are from the enumeration {@link pazmysaz.pyke.Widget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Presentation Type</em>' attribute.
   * @see pazmysaz.pyke.Widget
   * @see #setPresentationType(Widget)
   * @see pazmysaz.pyke.PykePackage#getSection_PresentationType()
   * @model
   * @generated
   */
  Widget getPresentationType();

  /**
   * Sets the value of the '{@link pazmysaz.pyke.Section#getPresentationType <em>Presentation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Presentation Type</em>' attribute.
   * @see pazmysaz.pyke.Widget
   * @see #getPresentationType()
   * @generated
   */
  void setPresentationType(Widget value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(String)
   * @see pazmysaz.pyke.PykePackage#getSection_Source()
   * @model
   * @generated
   */
  String getSource();

  /**
   * Sets the value of the '{@link pazmysaz.pyke.Section#getSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #getSource()
   * @generated
   */
  void setSource(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see pazmysaz.pyke.PykePackage#getSection_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link pazmysaz.pyke.Section#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // Section
