/*
 * generated by Xtext 2.25.0
 */
package pazmysaz.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PykeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DashboardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.Dashboard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDashboardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cIdentityAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cIdentityIdentityParserRuleCall_3_0 = (RuleCall)cIdentityAssignment_3.eContents().get(0);
		private final Assignment cLabelSummaryAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLabelSummaryLabelSummaryParserRuleCall_4_0 = (RuleCall)cLabelSummaryAssignment_4.eContents().get(0);
		private final Assignment cDistributionSummaryAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDistributionSummaryDistributionSummaryParserRuleCall_5_0 = (RuleCall)cDistributionSummaryAssignment_5.eContents().get(0);
		private final Assignment cTrendSummaryAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTrendSummaryTrendSummaryParserRuleCall_6_0 = (RuleCall)cTrendSummaryAssignment_6.eContents().get(0);
		private final Assignment cReportAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cReportReportParserRuleCall_7_0 = (RuleCall)cReportAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Dashboard:
		//    'dashboard' name=STRING
		//    '{'
		//       (identity=Identity)?
		//       (labelSummary=LabelSummary)?
		//       (distributionSummary?=DistributionSummary)?
		//       (trendSummary?=TrendSummary)?
		//       (report=Report)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'dashboard' name=STRING
		//'{'
		//   (identity=Identity)?
		//   (labelSummary=LabelSummary)?
		//   (distributionSummary?=DistributionSummary)?
		//   (trendSummary?=TrendSummary)?
		//   (report=Report)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'dashboard'
		public Keyword getDashboardKeyword_0() { return cDashboardKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(identity=Identity)?
		public Assignment getIdentityAssignment_3() { return cIdentityAssignment_3; }
		
		//Identity
		public RuleCall getIdentityIdentityParserRuleCall_3_0() { return cIdentityIdentityParserRuleCall_3_0; }
		
		//(labelSummary=LabelSummary)?
		public Assignment getLabelSummaryAssignment_4() { return cLabelSummaryAssignment_4; }
		
		//LabelSummary
		public RuleCall getLabelSummaryLabelSummaryParserRuleCall_4_0() { return cLabelSummaryLabelSummaryParserRuleCall_4_0; }
		
		//(distributionSummary?=DistributionSummary)?
		public Assignment getDistributionSummaryAssignment_5() { return cDistributionSummaryAssignment_5; }
		
		//DistributionSummary
		public RuleCall getDistributionSummaryDistributionSummaryParserRuleCall_5_0() { return cDistributionSummaryDistributionSummaryParserRuleCall_5_0; }
		
		//(trendSummary?=TrendSummary)?
		public Assignment getTrendSummaryAssignment_6() { return cTrendSummaryAssignment_6; }
		
		//TrendSummary
		public RuleCall getTrendSummaryTrendSummaryParserRuleCall_6_0() { return cTrendSummaryTrendSummaryParserRuleCall_6_0; }
		
		//(report=Report)?
		public Assignment getReportAssignment_7() { return cReportAssignment_7; }
		
		//Report
		public RuleCall getReportReportParserRuleCall_7_0() { return cReportReportParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class TrendSummaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.TrendSummary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTrendsummaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLhsSectionParserRuleCall_3_0 = (RuleCall)cLhsAssignment_3.eContents().get(0);
		private final Assignment cMhsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMhsSectionParserRuleCall_4_0 = (RuleCall)cMhsAssignment_4.eContents().get(0);
		private final Assignment cRhsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRhsSectionParserRuleCall_5_0 = (RuleCall)cRhsAssignment_5.eContents().get(0);
		private final Assignment cEdgeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEdgeSectionParserRuleCall_6_0 = (RuleCall)cEdgeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//TrendSummary:
		//    'trendsummary' name=STRING
		//    '{'
		//        lhs=Section
		//        (mhs=Section)?
		//        (rhs=Section)?
		//        (edge+=Section)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'trendsummary' name=STRING
		//'{'
		//    lhs=Section
		//    (mhs=Section)?
		//    (rhs=Section)?
		//    (edge+=Section)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'trendsummary'
		public Keyword getTrendsummaryKeyword_0() { return cTrendsummaryKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//lhs=Section
		public Assignment getLhsAssignment_3() { return cLhsAssignment_3; }
		
		//Section
		public RuleCall getLhsSectionParserRuleCall_3_0() { return cLhsSectionParserRuleCall_3_0; }
		
		//(mhs=Section)?
		public Assignment getMhsAssignment_4() { return cMhsAssignment_4; }
		
		//Section
		public RuleCall getMhsSectionParserRuleCall_4_0() { return cMhsSectionParserRuleCall_4_0; }
		
		//(rhs=Section)?
		public Assignment getRhsAssignment_5() { return cRhsAssignment_5; }
		
		//Section
		public RuleCall getRhsSectionParserRuleCall_5_0() { return cRhsSectionParserRuleCall_5_0; }
		
		//(edge+=Section)*
		public Assignment getEdgeAssignment_6() { return cEdgeAssignment_6; }
		
		//Section
		public RuleCall getEdgeSectionParserRuleCall_6_0() { return cEdgeSectionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class DistributionSummaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.DistributionSummary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDistributionsummaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLhsSectionParserRuleCall_3_0 = (RuleCall)cLhsAssignment_3.eContents().get(0);
		private final Assignment cMhsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMhsSectionParserRuleCall_4_0 = (RuleCall)cMhsAssignment_4.eContents().get(0);
		private final Assignment cRhsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRhsSectionParserRuleCall_5_0 = (RuleCall)cRhsAssignment_5.eContents().get(0);
		private final Assignment cEdgeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEdgeSectionParserRuleCall_6_0 = (RuleCall)cEdgeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		// DistributionSummary:
		//    'distributionsummary' name=STRING
		//    '{'
		//        lhs=Section
		//        (mhs=Section)?
		//        (rhs=Section)?
		//        (edge+=Section)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'distributionsummary' name=STRING
		//'{'
		//    lhs=Section
		//    (mhs=Section)?
		//    (rhs=Section)?
		//    (edge+=Section)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'distributionsummary'
		public Keyword getDistributionsummaryKeyword_0() { return cDistributionsummaryKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//lhs=Section
		public Assignment getLhsAssignment_3() { return cLhsAssignment_3; }
		
		//Section
		public RuleCall getLhsSectionParserRuleCall_3_0() { return cLhsSectionParserRuleCall_3_0; }
		
		//(mhs=Section)?
		public Assignment getMhsAssignment_4() { return cMhsAssignment_4; }
		
		//Section
		public RuleCall getMhsSectionParserRuleCall_4_0() { return cMhsSectionParserRuleCall_4_0; }
		
		//(rhs=Section)?
		public Assignment getRhsAssignment_5() { return cRhsAssignment_5; }
		
		//Section
		public RuleCall getRhsSectionParserRuleCall_5_0() { return cRhsSectionParserRuleCall_5_0; }
		
		//(edge+=Section)*
		public Assignment getEdgeAssignment_6() { return cEdgeAssignment_6; }
		
		//Section
		public RuleCall getEdgeSectionParserRuleCall_6_0() { return cEdgeSectionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class LabelSummaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.LabelSummary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLabelsummaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLhsSectionParserRuleCall_3_0 = (RuleCall)cLhsAssignment_3.eContents().get(0);
		private final Assignment cMhsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMhsSectionParserRuleCall_4_0 = (RuleCall)cMhsAssignment_4.eContents().get(0);
		private final Assignment cRhsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRhsSectionParserRuleCall_5_0 = (RuleCall)cRhsAssignment_5.eContents().get(0);
		private final Assignment cEdgeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEdgeSectionParserRuleCall_6_0 = (RuleCall)cEdgeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		// LabelSummary:
		//    'labelsummary' name=STRING
		//    '{'
		//        lhs=Section
		//        (mhs=Section)?
		//        (rhs=Section)?
		//        (edge+=Section)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'labelsummary' name=STRING
		//'{'
		//    lhs=Section
		//    (mhs=Section)?
		//    (rhs=Section)?
		//    (edge+=Section)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'labelsummary'
		public Keyword getLabelsummaryKeyword_0() { return cLabelsummaryKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//lhs=Section
		public Assignment getLhsAssignment_3() { return cLhsAssignment_3; }
		
		//Section
		public RuleCall getLhsSectionParserRuleCall_3_0() { return cLhsSectionParserRuleCall_3_0; }
		
		//(mhs=Section)?
		public Assignment getMhsAssignment_4() { return cMhsAssignment_4; }
		
		//Section
		public RuleCall getMhsSectionParserRuleCall_4_0() { return cMhsSectionParserRuleCall_4_0; }
		
		//(rhs=Section)?
		public Assignment getRhsAssignment_5() { return cRhsAssignment_5; }
		
		//Section
		public RuleCall getRhsSectionParserRuleCall_5_0() { return cRhsSectionParserRuleCall_5_0; }
		
		//(edge+=Section)*
		public Assignment getEdgeAssignment_6() { return cEdgeAssignment_6; }
		
		//Section
		public RuleCall getEdgeSectionParserRuleCall_6_0() { return cEdgeSectionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class IdentityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.Identity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIdentitylevelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLhsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLhsSectionParserRuleCall_3_0 = (RuleCall)cLhsAssignment_3.eContents().get(0);
		private final Assignment cMhsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMhsSectionParserRuleCall_4_0 = (RuleCall)cMhsAssignment_4.eContents().get(0);
		private final Assignment cRhsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRhsSectionParserRuleCall_5_0 = (RuleCall)cRhsAssignment_5.eContents().get(0);
		private final Assignment cEdgeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cEdgeSectionParserRuleCall_6_0 = (RuleCall)cEdgeAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Identity:
		//'identitylevel' name=STRING
		//    '{'
		//        lhs=Section
		//        (mhs=Section)?
		//        (rhs=Section)?
		//        (edge+=Section)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'identitylevel' name=STRING
		//    '{'
		//        lhs=Section
		//        (mhs=Section)?
		//        (rhs=Section)?
		//        (edge+=Section)*
		//    '}'
		public Group getGroup() { return cGroup; }
		
		//'identitylevel'
		public Keyword getIdentitylevelKeyword_0() { return cIdentitylevelKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//lhs=Section
		public Assignment getLhsAssignment_3() { return cLhsAssignment_3; }
		
		//Section
		public RuleCall getLhsSectionParserRuleCall_3_0() { return cLhsSectionParserRuleCall_3_0; }
		
		//(mhs=Section)?
		public Assignment getMhsAssignment_4() { return cMhsAssignment_4; }
		
		//Section
		public RuleCall getMhsSectionParserRuleCall_4_0() { return cMhsSectionParserRuleCall_4_0; }
		
		//(rhs=Section)?
		public Assignment getRhsAssignment_5() { return cRhsAssignment_5; }
		
		//Section
		public RuleCall getRhsSectionParserRuleCall_5_0() { return cRhsSectionParserRuleCall_5_0; }
		
		//(edge+=Section)*
		public Assignment getEdgeAssignment_6() { return cEdgeAssignment_6; }
		
		//Section
		public RuleCall getEdgeSectionParserRuleCall_6_0() { return cEdgeSectionParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ReportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.Report");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGridKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSectionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSectionSectionParserRuleCall_3_0 = (RuleCall)cSectionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Report:
		//    'grid' name=STRING
		//    '{'
		//        (section=Section)?
		//    '}'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//'grid' name=STRING
		//'{'
		//    (section=Section)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'grid'
		public Keyword getGridKeyword_0() { return cGridKeyword_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(section=Section)?
		public Assignment getSectionAssignment_3() { return cSectionAssignment_3; }
		
		//Section
		public RuleCall getSectionSectionParserRuleCall_3_0() { return cSectionSectionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.Section");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPresentedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cPresentationTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cPresentationTypeWidgetEnumRuleCall_2_0 = (RuleCall)cPresentationTypeAssignment_2.eContents().get(0);
		private final Keyword cFieldsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cSourceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cSourceSTRINGTerminalRuleCall_5_0 = (RuleCall)cSourceAssignment_5.eContents().get(0);
		private final Keyword cThroughKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cLeftCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cValueAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cValueSTRINGTerminalRuleCall_8_0 = (RuleCall)cValueAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Section:
		//    'presented' 'as' presentationType=Widget  'fields' 'from' source=STRING 'through'
		//    '{'
		//        value=STRING
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'presented' 'as' presentationType=Widget  'fields' 'from' source=STRING 'through'
		//'{'
		//    value=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'presented'
		public Keyword getPresentedKeyword_0() { return cPresentedKeyword_0; }
		
		//'as'
		public Keyword getAsKeyword_1() { return cAsKeyword_1; }
		
		//presentationType=Widget
		public Assignment getPresentationTypeAssignment_2() { return cPresentationTypeAssignment_2; }
		
		//Widget
		public RuleCall getPresentationTypeWidgetEnumRuleCall_2_0() { return cPresentationTypeWidgetEnumRuleCall_2_0; }
		
		//'fields'
		public Keyword getFieldsKeyword_3() { return cFieldsKeyword_3; }
		
		//'from'
		public Keyword getFromKeyword_4() { return cFromKeyword_4; }
		
		//source=STRING
		public Assignment getSourceAssignment_5() { return cSourceAssignment_5; }
		
		//STRING
		public RuleCall getSourceSTRINGTerminalRuleCall_5_0() { return cSourceSTRINGTerminalRuleCall_5_0; }
		
		//'through'
		public Keyword getThroughKeyword_6() { return cThroughKeyword_6; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7() { return cLeftCurlyBracketKeyword_7; }
		
		//value=STRING
		public Assignment getValueAssignment_8() { return cValueAssignment_8; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_8_0() { return cValueSTRINGTerminalRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	public class WidgetElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "pazmysaz.Pyke.Widget");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cReportcardEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cReportcardReportcardKeyword_0_0 = (Keyword)cReportcardEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEventilesEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEventilesEventilesKeyword_1_0 = (Keyword)cEventilesEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPieEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPiePieKeyword_2_0 = (Keyword)cPieEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cHistogramEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cHistogramHistogramKeyword_3_0 = (Keyword)cHistogramEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cDbarEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cDbarDbarKeyword_4_0 = (Keyword)cDbarEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cBadgeEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cBadgeBadgeKeyword_5_0 = (Keyword)cBadgeEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cGridEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cGridGridKeyword_6_0 = (Keyword)cGridEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum Widget:
		//    reportcard|eventiles|pie|histogram|dbar|badge|grid
		//;
		public EnumRule getRule() { return rule; }
		
		//reportcard|eventiles|pie|histogram|dbar|badge|grid
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//reportcard
		public EnumLiteralDeclaration getReportcardEnumLiteralDeclaration_0() { return cReportcardEnumLiteralDeclaration_0; }
		
		public Keyword getReportcardReportcardKeyword_0_0() { return cReportcardReportcardKeyword_0_0; }
		
		//eventiles
		public EnumLiteralDeclaration getEventilesEnumLiteralDeclaration_1() { return cEventilesEnumLiteralDeclaration_1; }
		
		public Keyword getEventilesEventilesKeyword_1_0() { return cEventilesEventilesKeyword_1_0; }
		
		//pie
		public EnumLiteralDeclaration getPieEnumLiteralDeclaration_2() { return cPieEnumLiteralDeclaration_2; }
		
		public Keyword getPiePieKeyword_2_0() { return cPiePieKeyword_2_0; }
		
		//histogram
		public EnumLiteralDeclaration getHistogramEnumLiteralDeclaration_3() { return cHistogramEnumLiteralDeclaration_3; }
		
		public Keyword getHistogramHistogramKeyword_3_0() { return cHistogramHistogramKeyword_3_0; }
		
		//dbar
		public EnumLiteralDeclaration getDbarEnumLiteralDeclaration_4() { return cDbarEnumLiteralDeclaration_4; }
		
		public Keyword getDbarDbarKeyword_4_0() { return cDbarDbarKeyword_4_0; }
		
		//badge
		public EnumLiteralDeclaration getBadgeEnumLiteralDeclaration_5() { return cBadgeEnumLiteralDeclaration_5; }
		
		public Keyword getBadgeBadgeKeyword_5_0() { return cBadgeBadgeKeyword_5_0; }
		
		//grid
		public EnumLiteralDeclaration getGridEnumLiteralDeclaration_6() { return cGridEnumLiteralDeclaration_6; }
		
		public Keyword getGridGridKeyword_6_0() { return cGridGridKeyword_6_0; }
	}
	
	private final DashboardElements pDashboard;
	private final TrendSummaryElements pTrendSummary;
	private final DistributionSummaryElements pDistributionSummary;
	private final LabelSummaryElements pLabelSummary;
	private final IdentityElements pIdentity;
	private final ReportElements pReport;
	private final SectionElements pSection;
	private final WidgetElements eWidget;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PykeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDashboard = new DashboardElements();
		this.pTrendSummary = new TrendSummaryElements();
		this.pDistributionSummary = new DistributionSummaryElements();
		this.pLabelSummary = new LabelSummaryElements();
		this.pIdentity = new IdentityElements();
		this.pReport = new ReportElements();
		this.pSection = new SectionElements();
		this.eWidget = new WidgetElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("pazmysaz.Pyke".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Dashboard:
	//    'dashboard' name=STRING
	//    '{'
	//       (identity=Identity)?
	//       (labelSummary=LabelSummary)?
	//       (distributionSummary?=DistributionSummary)?
	//       (trendSummary?=TrendSummary)?
	//       (report=Report)?
	//    '}';
	public DashboardElements getDashboardAccess() {
		return pDashboard;
	}
	
	public ParserRule getDashboardRule() {
		return getDashboardAccess().getRule();
	}
	
	//TrendSummary:
	//    'trendsummary' name=STRING
	//    '{'
	//        lhs=Section
	//        (mhs=Section)?
	//        (rhs=Section)?
	//        (edge+=Section)*
	//    '}'
	//;
	public TrendSummaryElements getTrendSummaryAccess() {
		return pTrendSummary;
	}
	
	public ParserRule getTrendSummaryRule() {
		return getTrendSummaryAccess().getRule();
	}
	
	// DistributionSummary:
	//    'distributionsummary' name=STRING
	//    '{'
	//        lhs=Section
	//        (mhs=Section)?
	//        (rhs=Section)?
	//        (edge+=Section)*
	//    '}'
	//;
	public DistributionSummaryElements getDistributionSummaryAccess() {
		return pDistributionSummary;
	}
	
	public ParserRule getDistributionSummaryRule() {
		return getDistributionSummaryAccess().getRule();
	}
	
	// LabelSummary:
	//    'labelsummary' name=STRING
	//    '{'
	//        lhs=Section
	//        (mhs=Section)?
	//        (rhs=Section)?
	//        (edge+=Section)*
	//    '}'
	//;
	public LabelSummaryElements getLabelSummaryAccess() {
		return pLabelSummary;
	}
	
	public ParserRule getLabelSummaryRule() {
		return getLabelSummaryAccess().getRule();
	}
	
	//Identity:
	//'identitylevel' name=STRING
	//    '{'
	//        lhs=Section
	//        (mhs=Section)?
	//        (rhs=Section)?
	//        (edge+=Section)*
	//    '}'
	//;
	public IdentityElements getIdentityAccess() {
		return pIdentity;
	}
	
	public ParserRule getIdentityRule() {
		return getIdentityAccess().getRule();
	}
	
	//Report:
	//    'grid' name=STRING
	//    '{'
	//        (section=Section)?
	//    '}'
	//    ;
	public ReportElements getReportAccess() {
		return pReport;
	}
	
	public ParserRule getReportRule() {
		return getReportAccess().getRule();
	}
	
	//Section:
	//    'presented' 'as' presentationType=Widget  'fields' 'from' source=STRING 'through'
	//    '{'
	//        value=STRING
	//    '}'
	//;
	public SectionElements getSectionAccess() {
		return pSection;
	}
	
	public ParserRule getSectionRule() {
		return getSectionAccess().getRule();
	}
	
	//enum Widget:
	//    reportcard|eventiles|pie|histogram|dbar|badge|grid
	//;
	public WidgetElements getWidgetAccess() {
		return eWidget;
	}
	
	public EnumRule getWidgetRule() {
		return getWidgetAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
