/*
 * generated by Xtext 2.25.0
 */
package pazmysaz.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link PykeWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractPykeWebModule extends DefaultWebModule {

}
