/*
 * generated by Xtext 2.25.0
 */
package pazmysaz;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PykeStandaloneSetup extends PykeStandaloneSetupGenerated {

	public static void doSetup() {
		new PykeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
